#!/usr/bin/env python3
"""Build Movie Shelf catalogue JS from collection.json.

Optionally import the legacy MovieCollection repo (catalogue + posters).
Never writes API keys. Posters stay gitignored; this only copies them on disk.

Usage (from repo root):
  python3 scripts/build-movie-shelf.py
  python3 scripts/build-movie-shelf.py --import-from /path/to/MovieCollection
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import shutil
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
APP_DIR = ROOT / "utilities" / "movie-shelf"
COLLECTION = APP_DIR / "collection.json"
MOVIES_JS = APP_DIR / "movies.js"
POSTERS_DIR = APP_DIR / "posters"

HOMES = {
    "hk": {"id": "hk", "label": "Hong Kong", "place": "Coral Court"},
    "penang": {"id": "penang", "label": "Penang", "place": "Tanjung Bungah"},
}

MOVIE_RE = re.compile(
    r'\{t:"((?:\\.|[^"\\])*)",y:(\d+),s:(\d+),l:"((?:\\.|[^"\\])*)"\}'
)


def film_id(title: str, year: int) -> str:
    slug = title.lower()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug.strip())
    slug = re.sub(r"-+", "-", slug).strip("-")
    return f"{slug}-{year}"


def load_collection() -> dict:
    data = json.loads(COLLECTION.read_text(encoding="utf-8"))
    data.setdefault("homes", HOMES)
    data.setdefault("movies", [])
    return data


def write_movies_js(data: dict) -> None:
    movies = data.get("movies", [])
    homes = data.get("homes", HOMES)
    MOVIES_JS.write_text(
        "// Generated by scripts/build-movie-shelf.py — edit collection.json via the local CMS.\n"
        "window.MOVIE_HOMES = "
        + json.dumps(homes, ensure_ascii=False, indent=2)
        + ";\nwindow.MOVIES = "
        + json.dumps(movies, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )


def import_legacy(src: pathlib.Path) -> dict:
    html = (src / "movie-randomizer.html").read_text(encoding="utf-8")
    manifest_path = src / "posters" / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.is_file() else {}

    movies = []
    seen = set()
    for title, year_s, _shelf, letterboxd in MOVIE_RE.findall(html):
        year = int(year_s)
        key = f"{title}_{year}"
        if key in seen:
            continue
        seen.add(key)
        fname = manifest.get(key)
        poster = fname if isinstance(fname, str) and fname else f"{film_id(title, year)}.jpg"
        movies.append(
            {
                "id": film_id(title, year),
                "t": title,
                "y": year,
                "home": None,
                "l": letterboxd,
                "poster": poster,
                "kind": "disc",
            }
        )

    POSTERS_DIR.mkdir(parents=True, exist_ok=True)
    src_posters = src / "posters"
    copied = 0
    if src_posters.is_dir():
        for movie in movies:
            src_file = src_posters / movie["poster"]
            if src_file.is_file():
                shutil.copy2(src_file, POSTERS_DIR / movie["poster"])
                copied += 1
            else:
                movie["poster"] = None

    trivia_src = src / "trivia.js"
    trivia_dst = APP_DIR / "trivia.js"
    if trivia_src.is_file():
        shutil.copy2(trivia_src, trivia_dst)

    data = {"homes": HOMES, "movies": movies}
    COLLECTION.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Imported {len(movies)} films, copied {copied} posters from {src}")
    return data


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Movie Shelf catalogue.")
    parser.add_argument(
        "--import-from",
        type=pathlib.Path,
        help="Legacy MovieCollection directory (one-time import).",
    )
    args = parser.parse_args()

    APP_DIR.mkdir(parents=True, exist_ok=True)
    POSTERS_DIR.mkdir(parents=True, exist_ok=True)

    if args.import_from:
        src = args.import_from.expanduser().resolve()
        if not (src / "movie-randomizer.html").is_file():
            print(f"ERROR: no movie-randomizer.html in {src}", file=sys.stderr)
            return 1
        data = import_legacy(src)
    else:
        if not COLLECTION.is_file():
            print(f"ERROR: missing {COLLECTION}", file=sys.stderr)
            return 1
        data = load_collection()

    write_movies_js(data)
    print(f"Wrote {MOVIES_JS.relative_to(ROOT)} ({len(data.get('movies', []))} films)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
