/* Shared helpers for the Mee-Search prototypes.
 *
 * Loads the graph, builds an index, and provides the chrome each view reuses:
 * tooltip, detail panel, legend, confidence styling.
 *
 * Data source: graph-data.js sets window.MEE_GRAPH (works on file://).
 * If that is absent we fall back to fetching ../data/noodle-graph.json, which
 * needs a web server. Both are generated by tools/build_graph.py.
 */
(function (global) {
  "use strict";

  const MEE = {};

  /* ------------------------------------------------------------- loading */

  MEE.load = async function () {
    if (global.MEE_GRAPH) return MEE.index(global.MEE_GRAPH);
    const res = await fetch("../data/noodle-graph.json");
    if (!res.ok) throw new Error("could not load graph data");
    return MEE.index(await res.json());
  };

  /* --------------------------------------------------------------- index */

  MEE.index = function (raw) {
    const g = {
      meta: raw.meta,
      sources: raw.sources,
      nodes: raw.nodes,
      edges: raw.edges,
      byId: Object.create(null),
      out: Object.create(null),
      in: Object.create(null),
      byType: Object.create(null),
    };

    for (const n of g.nodes) {
      g.byId[n.id] = n;
      g.out[n.id] = [];
      g.in[n.id] = [];
      (g.byType[n.type] || (g.byType[n.type] = [])).push(n);
    }
    for (const e of g.edges) {
      g.out[e.source].push(e);
      g.in[e.target].push(e);
    }

    // degree, used for sizing almost everywhere
    for (const n of g.nodes) {
      n.degree = g.out[n.id].length + g.in[n.id].length;
    }

    /* neighbours of a node, optionally filtered by edge type and direction */
    g.neighbours = function (id, types, dir) {
      const want = types ? new Set([].concat(types)) : null;
      const acc = [];
      if (dir !== "in") {
        for (const e of g.out[id]) {
          if (!want || want.has(e.type)) acc.push({ edge: e, node: g.byId[e.target], dir: "out" });
        }
      }
      if (dir !== "out") {
        for (const e of g.in[id]) {
          if (!want || want.has(e.type)) acc.push({ edge: e, node: g.byId[e.source], dir: "in" });
        }
      }
      return acc;
    };

    /* every cultural thread present in a dish, assembled from its components.
       This is the `contributed_by` walk the schema is built for. */
    g.threadsOf = function (dishId) {
      const tally = Object.create(null);
      const add = (cid, w, via, viaType) => {
        const t = tally[cid] || (tally[cid] = { culture: g.byId[cid], weight: 0, via: [] });
        t.weight += w;
        t.via.push({ node: g.byId[via], type: viaType });
      };
      // direct attribution
      for (const e of g.out[dishId]) {
        if (e.type === "carried_by") add(e.target, e.weight * 2.2, dishId, "carried_by");
        if (e.type === "attributed_to") add(e.target, e.weight * 1.1, dishId, "attributed_to");
      }
      // components, and who contributed each
      for (const e of g.out[dishId]) {
        if (!/^uses_/.test(e.type)) continue;
        for (const c of g.out[e.target]) {
          if (c.type === "contributed_by") {
            add(c.target, e.weight * c.weight, e.target, e.type);
          }
        }
      }
      return Object.values(tally).sort((a, b) => b.weight - a.weight);
    };

    return g;
  };

  /* -------------------------------------------------------------- labels */

  MEE.TYPE_LABEL = {
    region: "Region",
    culture: "Community",
    wave: "Migration wave",
    dish: "Dish",
    noodle: "Noodle",
    ingredient: "Ingredient",
    technique: "Technique",
    commodity: "Commodity",
    media: "Media event",
    concept: "Concept",
    name: "Name collision",
    venue: "Venue",
    episode: "Episode",
  };

  MEE.EDGE_LABEL = {
    home_region: "from",
    settled_in: "settled in",
    migrated_via: "moved by",
    occupied_niche: "niche",
    originates_in: "origin",
    carried_by: "cooked by",
    attributed_to: "claimed",
    uses_noodle: "noodle",
    uses_ingredient: "uses",
    uses_technique: "method",
    contributed_by: "from",
    derived_from: "descends",
    sibling_of: "sibling",
    influenced_by: "borrows",
    halal_variant_of: "halal pair",
    shares_architecture: "same shape",
    co_sold_with: "same stall",
    confused_with: "confused",
    false_cognate_of: "false cognate",
    unevidenced_link: "refused",
    enabled_by: "enabled by",
    standardised_by: "standardised",
    popularised_by: "popularised",
    ritual_role: "ritual",
    illustrates: "illustrates",
    of_dish: "dish",
    tasted_at: "tasted at",
    revisit_of: "revisit of",
    reference_stall_for: "benchmark",
  };

  MEE.CONF_ALPHA = { high: 0.5, medium: 0.34, low: 0.2, disputed: 0.62 };
  MEE.CONF_DASH = { high: null, medium: null, low: "2 3", disputed: "5 3" };
  MEE.CONF_ORDER = ["high", "medium", "low", "disputed"];

  MEE.colour = (n) => (n && n.colour) || "#888";
  /* `tone` distinguishes individual communities; `colour` distinguishes node types.
     Use tone wherever a single bowl can receive several kitchens at once. */
  MEE.tone = (n) => (n && (n.tone || n.colour)) || "#888";

  /* ------------------------------------------------------------- tooltip */

  MEE.tooltip = function () {
    const el = document.createElement("div");
    el.className = "viz-tip";
    document.body.appendChild(el);
    let raf = null;
    return {
      show(evt, node, extra) {
        const type = MEE.TYPE_LABEL[node.type] || node.type;
        el.innerHTML =
          '<span class="t-type">' +
          MEE.esc(type) +
          "</span>" +
          MEE.esc(node.label) +
          (extra ? '<span class="t-type" style="opacity:.8;margin-top:3px">' + MEE.esc(extra) + "</span>" : "");
        el.dataset.open = "true";
        this.move(evt);
      },
      move(evt) {
        if (raf) return;
        raf = requestAnimationFrame(() => {
          raf = null;
          const pad = 14;
          const r = el.getBoundingClientRect();
          let x = evt.clientX + pad;
          let y = evt.clientY + pad;
          if (x + r.width > innerWidth - 8) x = evt.clientX - r.width - pad;
          if (y + r.height > innerHeight - 8) y = evt.clientY - r.height - pad;
          el.style.left = x + "px";
          el.style.top = y + "px";
        });
      },
      hide() {
        el.dataset.open = "false";
      },
    };
  };

  /* --------------------------------------------------------------- panel */

  /* Builds the detail panel. `onNav` receives a node id when the reader
     clicks a related node, so each view can decide what "go there" means. */
  /* `opts.host` renders the dossier into an element you supply — a fixed column
     beside the stage — instead of floating it over the view. Use it whenever the
     subject is centred and an overlay would cover its own labels. */
  MEE.panel = function (stage, onNav, opts) {
    opts = opts || {};
    const fixed = !!opts.host;
    const el = opts.host || document.createElement("aside");
    el.classList.add("viz-panel");
    if (fixed) el.classList.add("viz-panel--fixed");
    el.setAttribute("aria-live", "polite");

    /* The scrolling region is a persistent child rather than the panel itself:
       that lets the fade overlay survive innerHTML replacement, and it means a
       long dossier can run the full height of the stage without appearing to
       stop mid-sentence. */
    const body = document.createElement("div");
    body.className = "p-body";
    const fade = document.createElement("div");
    fade.className = "p-fade";
    el.appendChild(body);
    el.appendChild(fade);
    if (!fixed) stage.appendChild(el);
    el.dataset.open = fixed ? "true" : "false";

    function syncFade() {
      const more = body.scrollHeight - body.clientHeight - body.scrollTop > 6;
      el.dataset.more = more ? "true" : "false";
    }
    body.addEventListener("scroll", syncFade, { passive: true });
    if (window.ResizeObserver) new ResizeObserver(syncFade).observe(body);

    el.addEventListener("click", (e) => {
      const b = e.target.closest("button[data-nav]");
      if (b && onNav) onNav(b.dataset.nav);
      if (e.target.closest(".p-close")) api.close();
    });

    const api = {
      el,
      fixed,
      close() {
        // a fixed dossier has nothing to close; leave the last selection up
        if (!fixed) el.dataset.open = "false";
      },
      show(node, g, opts) {
        opts = opts || {};
        const alt = []
          .concat(node.zh || [], node.aka || [], node.malay || [], node.tamil || [])
          .filter(Boolean)
          .join(" · ");

        let h =
          (fixed ? "" : '<button class="p-close" aria-label="Close">&times;</button>') +
          '<p class="p-type">' +
          MEE.esc(MEE.TYPE_LABEL[node.type] || node.type) +
          "</p>" +
          "<h3>" +
          MEE.esc(node.label) +
          "</h3>";
        if (alt) h += '<p class="p-alt">' + MEE.esc(alt) + "</p>";

        if (node.confidence) h += '<p style="margin-top:8px">' + MEE.confBadge(node.confidence) + "</p>";
        for (const f of node.flags || []) h += '<span class="flagpill">' + MEE.esc(f) + "</span>";

        const dl = [];
        if (node.penangStatus) dl.push(["In Penang", node.penangStatus]);
        if (node.tryStatus && node.tryStatus !== "off-list") dl.push(["Series", node.tryStatus]);
        if (node.style) dl.push(["Style", node.style]);
        if (node.arrival) dl.push(["Arrival", node.arrival]);
        if (node.penangShare) dl.push(["Share", node.penangShare]);
        if (node.period) dl.push(["Period", node.period]);
        if (node.date) dl.push(["Date", node.date]);
        if (node.founded) dl.push(["Founded", node.founded]);
        if (node.area) dl.push(["Where", node.area]);
        if (node.material) dl.push(["Material", node.material]);
        if (node.marker) dl.push(["Marker", node.marker]);
        if (node.country && node.admin) dl.push(["Place", node.admin + ", " + node.country]);
        else if (node.country) dl.push(["Place", node.country]);
        if (dl.length) {
          h += "<dl>";
          for (const [k, v] of dl) h += "<dt>" + MEE.esc(k) + "</dt><dd>" + MEE.esc(v) + "</dd>";
          h += "</dl>";
        }

        for (const key of ["blurb", "etymology", "penangVariation", "fusion", "ritual", "significance", "niche", "note"]) {
          if (node[key]) h += '<p class="p-blurb">' + MEE.rich(node[key]) + "</p>";
        }
        if (node.contested) h += '<p class="p-note"><strong>Contested.</strong> ' + MEE.rich(node.contested) + "</p>";

        /* A view can append its own block here — after the prose, so the description
           keeps the top of the panel. Used by 04 for the thread breakdown. */
        if (opts.inject) h += opts.inject;

        if (node.postSlug) {
          h +=
            '<p style="margin-top:10px"><a style="color:var(--accent);font-weight:600" target="_blank" rel="noopener" href="https://penangpulse.com/guides/' +
            MEE.esc(node.postSlug) +
            '/">Read the episode &rarr;</a></p>';
        }

        if (opts.related !== false && g) {
          const rel = g
            .neighbours(node.id)
            .filter((r) => r.node)
            .sort((a, b) => b.edge.weight - a.edge.weight)
            .slice(0, opts.relatedLimit || 12);
          if (rel.length) {
            h += '<ul class="p-links">';
            for (const r of rel) {
              h +=
                "<li>" +
                '<span class="l-type">' +
                MEE.esc(MEE.EDGE_LABEL[r.edge.type] || r.edge.type) +
                "</span>" +
                '<button data-nav="' +
                MEE.esc(r.node.id) +
                '">' +
                MEE.esc(r.node.label) +
                "</button>" +
                "</li>";
            }
            h += "</ul>";
          }
        }

        if (node.sources && node.sources.length && g && g.sources) {
          const s = node.sources
            .map((id) => g.sources[id])
            .filter(Boolean)
            .slice(0, 4);
          if (s.length) {
            h +=
              '<p class="p-note"><strong>Sources.</strong> ' +
              s
                .map(
                  (x) =>
                    '<a target="_blank" rel="noopener" style="color:var(--accent)" href="' +
                    MEE.esc(x.url) +
                    '">' +
                    MEE.esc(MEE.shortSource(x.title)) +
                    "</a>"
                )
                .join(" · ") +
              "</p>";
          }
        }

        body.innerHTML = h;
        el.dataset.open = "true";
        body.scrollTop = 0;
        syncFade();
      },

      /* a panel view for an edge rather than a node */
      showEdge(edge, g) {
        const s = g.byId[edge.source];
        const t = g.byId[edge.target];
        let h =
          (fixed ? "" : '<button class="p-close" aria-label="Close">&times;</button>') +
          '<p class="p-type">' +
          MEE.esc(MEE.EDGE_LABEL[edge.type] || edge.type) +
          "</p>" +
          "<h3>" +
          MEE.esc(s.label) +
          '<span style="color:var(--muted);font-weight:400"> &rarr; </span>' +
          MEE.esc(t.label) +
          "</h3>" +
          '<p style="margin-top:8px">' +
          MEE.confBadge(edge.confidence) +
          '<span style="color:var(--muted);font-size:.8rem;margin-left:8px">weight ' +
          edge.weight.toFixed(2) +
          "</span></p>";
        if (edge.note) h += '<p class="p-blurb">' + MEE.rich(edge.note) + "</p>";
        h +=
          '<ul class="p-links"><li><span class="l-type">go to</span><button data-nav="' +
          s.id +
          '">' +
          MEE.esc(s.label) +
          '</button></li><li><span class="l-type">go to</span><button data-nav="' +
          t.id +
          '">' +
          MEE.esc(t.label) +
          "</button></li></ul>";
        body.innerHTML = h;
        el.dataset.open = "true";
        body.scrollTop = 0;
        syncFade();
      },
    };
    return api;
  };

  MEE.confBadge = (c) => '<span class="conf conf-' + c + '">' + c + "</span>";

  MEE.shortSource = function (title) {
    const t = String(title).split(/,| - | — |\(/)[0].trim();
    return t.length > 42 ? t.slice(0, 40) + "…" : t;
  };

  /* Minimal inline markdown for prose fields. The dataset legitimately contains
     **bold** in a few notes (it is also read by the narrative), so escape first and
     then re-introduce only <strong> — never raw HTML from the data. */
  MEE.rich = function (str) {
    return MEE.esc(str).replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  };

  MEE.esc = function (s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;",
    }[c]));
  };

  /* -------------------------------------------------------------- legend */

  /* items: [{key,label,colour,line}] — returns a toggle-state object */
  MEE.legend = function (host, items, onToggle) {
    const off = new Set();
    host.className = "viz-legend";
    host.innerHTML = "";
    for (const it of items) {
      const b = document.createElement("button");
      b.type = "button";
      b.innerHTML =
        '<span class="swatch' +
        (it.line ? " swatch-line" : "") +
        '" style="' +
        (it.line ? "border-top-color:" + it.colour + ";border-top-style:" + (it.dash || "solid") : "background:" + it.colour) +
        '"></span>' +
        MEE.esc(it.label);
      b.addEventListener("click", () => {
        if (off.has(it.key)) off.delete(it.key);
        else off.add(it.key);
        b.dataset.off = off.has(it.key) ? "true" : "false";
        if (onToggle) onToggle(off);
      });
      host.appendChild(b);
    }
    return off;
  };

  /* ------------------------------------------------------------ plumbing */

  MEE.size = function (stage) {
    const r = stage.getBoundingClientRect();
    return { w: Math.max(320, r.width), h: Math.max(320, r.height) };
  };

  /* debounced resize that also fires once immediately */
  MEE.onResize = function (fn) {
    let t = null;
    const run = () => {
      clearTimeout(t);
      t = setTimeout(fn, 160);
    };
    addEventListener("resize", run);
    fn();
  };

  MEE.reducedMotion = () =>
    global.matchMedia && global.matchMedia("(prefers-reduced-motion: reduce)").matches;

  /* Nudges a d3 force simulation without the "jump" of a full restart. */
  MEE.kick = function (sim, alpha) {
    sim.alpha(alpha == null ? 0.5 : alpha).restart();
  };

  /* Short, readable label for crowded views. */
  MEE.short = function (label, n) {
    n = n || 22;
    const s = String(label).replace(/\s*\(.*?\)\s*/g, " ").trim();
    return s.length > n ? s.slice(0, n - 1) + "…" : s;
  };

  MEE.fail = function (stage, err) {
    console.error(err);
    stage.insertAdjacentHTML(
      "beforeend",
      '<div style="position:absolute;inset:0;display:grid;place-items:center;padding:24px;text-align:center;color:var(--muted);font-size:.9rem">' +
        "Could not load the graph data.<br>Run <code>python3 tools/build_graph.py</code>, " +
        "or serve this folder over http.</div>"
    );
  };

  global.MEE = MEE;
})(window);
